class Rifle;
class Rifle_Base_F: Rifle
{
    class WeaponSlotsInfo;
};
class UGL_F;

class THOR_FNP90_base: Rifle_Base_F
{ 
    scope=0;
    magazines[]=
    {
        "THOR_FNP90_Mag",
        "THOR_FNP90_Mag_Tracer"
    };
    reloadAction="GestureReloadSMG_02";
    maxZeroing=600;
    cursor="smg";
    discreteDistance[]={100,200};
    discreteDistanceInitIndex=0;
    aiDispersionCoefY=8;
    aiDispersionCoefX=9;
    descriptionShort="$STR_THOR_FNP90_Desc";
    handAnim[]=
    {
        "OFP2_ManSkeleton",
        "\A3\Weapons_F_beta\Smgs\SMG_02\data\Anim\SMG_02.rtm"
    }; 
    class WeaponSlotsInfo: WeaponSlotsInfo
    {
        class MuzzleSlot: MuzzleSlot
        {
            linkProxy="\A3\data_f\proxies\weapon_slots\MUZZLE";
            compatibleItems[]=
            {
                "muzzle_snds_l"
            };
            iconPosition[]={0.079999998,0.40000001};
            iconScale=0.2;
        };
        class CowsSlot: CowsSlot
        {
            iconPosition[]={0.44999999,0.27000001};
            iconScale=0.2;
        };
        class PointerSlot: PointerSlot
        {
            iconPosition[]={0.28,0.40000001};
            iconScale=0.25;
        };
    };
    bullet1[]=
    {
        "A3\sounds_f\weapons\shells\9mm\metal_9mm_01",
        0.50118721,
        1,
        15
    };
    bullet2[]=
    {
        "A3\sounds_f\weapons\shells\9mm\metal_9mm_02",
        0.50118721,
        1,
        15
    };
    bullet3[]=
    {
        "A3\sounds_f\weapons\shells\9mm\metal_9mm_03",
        0.50118721,
        1,
        15
    };
    bullet4[]=
    {
        "A3\sounds_f\weapons\shells\9mm\metal_9mm_04",
        0.50118721,
        1,
        15
    };
    bullet5[]=
    {
        "A3\sounds_f\weapons\shells\9mm\dirt_9mm_01",
        0.50118721,
        1,
        15
    };
    bullet6[]=
    {
        "A3\sounds_f\weapons\shells\9mm\dirt_9mm_02",
        0.50118721,
        1,
        15
    };
    bullet7[]=
    {
        "A3\sounds_f\weapons\shells\9mm\dirt_9mm_03",
        0.50118721,
        1,
        15
    };
    bullet8[]=
    {
        "A3\sounds_f\weapons\shells\9mm\dirt_9mm_04",
        0.50118721,
        1,
        15
    };
    bullet9[]=
    {
        "A3\sounds_f\weapons\shells\9mm\grass_9mm_01",
        0.39810717,
        1,
        15
    };
    bullet10[]=
    {
        "A3\sounds_f\weapons\shells\9mm\grass_9mm_02",
        0.39810717,
        1,
        15
    };
    bullet11[]=
    {
        "A3\sounds_f\weapons\shells\9mm\grass_9mm_03",
        0.39810717,
        1,
        15
    };
    bullet12[]=
    {
        "A3\sounds_f\weapons\shells\9mm\grass_9mm_04",
        0.39810717,
        1,
        15
    };
    soundBullet[]=
    {
        "bullet1",
        0.082999997,
        "bullet2",
        0.082999997,
        "bullet3",
        0.082999997,
        "bullet4",
        0.082999997,
        "bullet5",
        0.082999997,
        "bullet6",
        0.082999997,
        "bullet7",
        0.082999997,
        "bullet8",
        0.082999997,
        "bullet9",
        0.082999997,
        "bullet10",
        0.082999997,
        "bullet11",
        0.082999997,
        "bullet12",
        0.082999997
    };
    opticsZoomMin=0.375;
    opticsZoomMax=1.1;
    opticsZoomInit=0.75;
    distanceZoomMin=100;
    distanceZoomMax=100;
    modes[]=
    {
        "Single",
        "Burst",
        "FullAuto"
    };
    drySound[]=
    {
        "A3\Sounds_F\arsenal\weapons\SMG\Sting\Dry_Sting",
        0.25118864,
        1,
        10
    };
    reloadMagazineSound[]=
    {
        "A3\Sounds_F\arsenal\weapons\SMG\Sting\reload_sting",
        1,
        1,
        10
    };
    changeFiremodeSound[]=
    {
        "A3\Sounds_F\arsenal\weapons\SMG\Sting\firemode_Sting",
        0.25118864,
        1,
        5
    };
    class Single: Mode_SemiAuto
    {
        sounds[]=
        {
            "StandardSound",
            "SilencedSound"
        };
        class BaseSoundModeType
        {
            weaponSoundEffect="DefaultRifle";
            closure1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_01",
                1,
                1,
                10
            };
            closure2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_02",
                1,
                1.1,
                10
            };
            soundClosure[]=
            {
                "closure1",
                0.5,
                "closure2",
                0.5
            };
        };
        class StandardSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_01",
                1,
                1,
                1200
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_02",
                1,
                1,
                1200
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_03",
                1,
                1,
                1200
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        class SilencedSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_01",
                0.89125091,
                1,
                400
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_02",
                0.89125091,
                1,
                400
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_03",
                0.89125091,
                1,
                400
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        reloadTime=0.054499999;
        dispersion=0.0011;
        recoil="recoil_single_smg_02";
        recoilProne="recoil_single_prone_smg_02";
        minRange=2;
        minRangeProbab=0.30000001;
        midRange=100;
        midRangeProbab=0.69999999;
        maxRange=150;
        maxRangeProbab=0.050000001;
        aiRateOfFire=2;
        aiRateOfFireDistance=300;
    };
    class Burst: Mode_Burst
    {
        sounds[]=
        {
            "StandardSound",
            "SilencedSound"
        };
        class BaseSoundModeType
        {
            weaponSoundEffect="DefaultRifle";
            closure1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_01",
                1,
                1,
                10
            };
            closure2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_02",
                1,
                1.1,
                10
            };
            soundClosure[]=
            {
                "closure1",
                0.5,
                "closure2",
                0.5
            };
        };
        class StandardSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_01",
                1,
                1,
                1200
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_02",
                1,
                1,
                1200
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_03",
                1,
                1,
                1200
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        class SilencedSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_01",
                0.89125091,
                1,
                400
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_02",
                0.89125091,
                1,
                400
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_03",
                0.89125091,
                1,
                400
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        soundBurst=0;
        burst=3;
        reloadTime=0.054499999;
        dispersion=0.0011;
        recoil="recoil_burst_smg_02";
        recoilProne="recoil_burst_prone_smg_02";
        minRange=2;
        minRangeProbab=0.30000001;
        midRange=50;
        midRangeProbab=0.69999999;
        maxRange=100;
        maxRangeProbab=0.050000001;
        aiRateOfFire=1;
        aiRateOfFireDistance=250;
    };
    class FullAuto: Mode_FullAuto
    {
        sounds[]=
        {
            "StandardSound",
            "SilencedSound"
        };
        class BaseSoundModeType
        {
            weaponSoundEffect="DefaultRifle";
            closure1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_01",
                1,
                1,
                10
            };
            closure2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\closure_Sting_02",
                1,
                1.1,
                10
            };
            soundClosure[]=
            {
                "closure1",
                0.5,
                "closure2",
                0.5
            };
        };
        class StandardSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_01",
                1,
                1,
                1200
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_02",
                1,
                1,
                1200
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Sting_03",
                1,
                1,
                1200
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        class SilencedSound: BaseSoundModeType
        {
            begin1[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_01",
                0.89125091,
                1,
                400
            };
            begin2[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_02",
                0.89125091,
                1,
                400
            };
            begin3[]=
            {
                "A3\Sounds_F\arsenal\weapons\SMG\Sting\Silencer_Sting_03",
                0.89125091,
                1,
                400
            };
            soundBegin[]=
            {
                "begin1",
                0.33000001,
                "begin2",
                0.33000001,
                "begin3",
                0.34
            };
        };
        reloadTime=0.069499999;
        dispersion=0.0011;
        recoil="recoil_auto_smg_02";
        recoilProne="recoil_auto_prone_smg_02";
        minRange=0;
        minRangeProbab=0.89999998;
        midRange=15;
        midRangeProbab=0.69999999;
        maxRange=30;
        maxRangeProbab=0.1;
        aiRateOfFire=1e-006;
        aiRateOfFireDistance=50;
    };
    class UGL_F: UGL_F
    {
    };
};

class THOR_FNP90: THOR_FNP90_base
{
    author="[THOR]Heron";
    _generalMacro="SMG_02_F";
    scope=2;
    model="\THOR_FNP90_FiveSeven\data\THOR_FNP90.p3d";
    class WeaponSlotsInfo: WeaponSlotsInfo
    {
	class CowsSlot {
		access = 1;
		compatibleitems[] = {"optic_Arco", "optic_aco", "optic_ACO_grn", "optic_hamr", "optic_Holosight"};
		displayname = "Optics Slot";
		linkproxy = "\A3\data_f\proxies\weapon_slots\TOP";
		scope = 2;
	};
     mass=60;
    };
    inertia=0.40000001;
    dexterity=1.6;
    initSpeed=370;
    displayName="$STR_THOR_FNP90";
    picture="\A3\Weapons_F_beta\Smgs\SMG_02\Data\UI\gear_smg_02_X_CA.paa";
    UiPicture="\A3\Weapons_F\data\UI\icon_regular_CA.paa";
    class Library
    {
        libTextDesc="$STR_THOR_FNP90_Library";
    };
    descriptionShort="$STR_THOR_FNP90_Desc";
};